name: Build & Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  native:
    strategy:
      matrix:
        go: [ '1.22', '1.23', 1.24.x, 1.25.x, 1.26.x ]
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          # Go 1.22.x setup fails on macOS runners: https://stackoverflow.com/a/79790775
          - go-version: 1.22.x
            os: macos-latest
          - go-version: 1.23.x
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go ${{ matrix.go }}
        # https://github.com/actions/setup-go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        # https://github.com/actions/checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Build project
        run: make build
      - name: Execute CLI help
        run: ./cobbler --help
      - name: Upload binary Artifact
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: cobbler-cli-binary-${{ matrix.go }}-${{ matrix.os }}
          path: ./cobbler
  rpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # https://github.com/actions/checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Build RPM
        run: make build-rpm-docker
      - name: Upload RPM Artifact
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: cobbler-cli-native-rpm
          path: ./rpms/**/*.rpm
  deb:
    # This will fail until Debian 13 will arrive with a newer golang version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # https://github.com/actions/checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Build DEB
        continue-on-error: true
        run: make build-deb-docker
      - name: Upload DEB Artifact
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: cobbler-cli-native-deb
          path: ./debs/**/*.deb
  docker:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      PUSH_IMAGE: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        # https://github.com/actions/checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Log in to GHCR
        # https://github.com/docker/login-action
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        # https://github.com/docker/metadata-action
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        # https://github.com/docker/build-push-action
        id: push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: .
          file: ./packaging/docker/production/Dockerfile
          push: ${{ env.PUSH_IMAGE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        # https://github.com/actions/attest-build-provenance
        uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018 # v1.4.4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: ${{ env.PUSH_IMAGE }}
  goreleaser:
    runs-on: ubuntu-latest
    needs:
      - native
      - docker
      - deb
      - rpm
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - name: Set up Go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      - name: Download all artifacts
        # https://github.com/actions/download-artifact
        id: download-artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          pattern: "cobbler-cli-native-*"
      - name: Import GPG key
        # https://github.com/crazy-max/ghaction-import-gpg
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser (tag)
        # https://github.com/goreleaser/goreleaser-action
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser (draft)
        # https://github.com/goreleaser/goreleaser-action
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          version: latest
          args: release --snapshot --clean
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
