name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  native:
    strategy:
      matrix:
        go: [ '1.22', '1.23' ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: make build
      - name: Execute CLI help
        run: ./cobbler --help
      - name: Upload binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cobbler-cli-binary-${{ matrix.go }}-${{ matrix.os }}
          path: ./cobbler
  rpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build RPM
        run: make build-rpm-docker
      - name: Upload RPM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cobbler-cli-rpm
          path: ./rpms/**/*.rpm
