on: [push, pull_request]
name: Build
jobs:
  build:
    strategy:
      matrix:
        go: [ '1.17' ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: go build -o cli main.go
      - name: Execute CLI
        run: ./cli
