name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      # https://github.com/actions/checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: Set up Python
      # https://github.com/actions/setup-python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: 3.9
    - name: Install dependencies
      run:  pip install -U rstcheck doc8 sphinx
    - name: Run rstcheck
      run:  rstcheck -r docs
    - name: Run doc8
      run: doc8 --ignore D001 docs
  lint_go:
    name: Linting Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # https://github.com/actions/checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Set up Go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: stable
      - name: golangci-lint
        # https://github.com/golangci/golangci-lint-action
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.9.0
