name: testing

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Integration Tests (Cobbler ${{ matrix.cobbler_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cobbler_version:
          - 2f0ff03f17ae957cac65d9ef033a98e8d597145a # v4.0.0a4
      fail-fast: false
    steps:
      - name: Check out code into the Go module directory
        # https://github.com/actions/checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Set up Go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: 'go.mod'
        id: go
      - name: Install system dependencies
        run: |
          sudo apt-get install -y xorriso
      - name: Get dependencies
        run: |
          go mod download
      - name: Replace git version hash
        run: |
          sed -i "s/cobbler_commit=.*/cobbler_commit=${{ matrix.cobbler_version }}/" testing/start.sh
      - name: Restore OS ISO
        id: cache-iso-restore
        # https://github.com/actions/cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            *.iso
          key: ${{ runner.os }}-${{ matrix.cobbler_version }}-iso
      - name: Make Test
        run: |
          make test
      - name: Save OS ISO
        id: cache-iso-save
        # https://github.com/actions/cache
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            *.iso
          key: ${{ steps.cache-iso-restore.outputs.cache-primary-key }}
      - name: Upload coverage report to GH artifacts
        if: matrix.cobbler_version == 'df356046f3cf27be62a61001b982d5983800cfd9'
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-report
          path: coverage.out
          if-no-files-found: error
